final List<List<Map<String, String>>> dailyPuzzleData = [
  [{ 'word': 'BİRDENBİRE', 'hint': 'Ansızın'},],
  [{ 'word': 'ACEMAŞİRAN', 'hint': 'Klasik Türk müziğinde kullanılan şet makamlarından biri'},],
  [{ 'word': 'KIZILIRMAK', 'hint': 'Çankırı iline bağlı ilçelerden biri'},],
  [{ 'word': 'İNİSİYATİF', 'hint': 'Karar verme yetkisi, Gerekli kararları almayı bilen kişinin niteliği'},],
  [{ 'word': 'AYAKTAKIMI', 'hint': 'Görgüsüzlükleri veya bilgisizlikleri dolayısıyla toplum içinde aşağı durumda olan kişiler, lümpen, parya'},],
  [{ 'word': 'LİKİDASYON', 'hint': 'Tasfiye'},],
  [{ 'word': 'KAPLUMBAĞA', 'hint': 'Çok sert ve kemiksi bir kabuk içinde yaşayan, ağır ağır yürüyen, dört ayaklı, sürüngen hayvan (Testudo)'},],
  [{ 'word': 'REKREASYON', 'hint': 'İnsanların boş zamanlarında, eğlence ve spor amacı ile gönüllü olarak katıldıkları etkinlikler'},],
  [{ 'word': 'PARLAMENTO', 'hint': 'Başlıca görevi yasama, devlet bütçesini çıkarma, hükûmeti denetleme olan ve üyeleri halkoyu ile belirli bir süre için seçilen meclis veya meclisler, yasama kurulu, yasama meclisi, yasama organı'},],
  [{ 'word': 'KURBAĞACIK', 'hint': 'Ayarlanabilir somun anahtarı'},],
  [{ 'word': 'ÇİFTETELLİ', 'hint': 'Göğüs ve göbek titreterek, gerdan kırarak oynanan bir oyun'},],
  [{ 'word': 'DEĞİŞTİRGE', 'hint': 'Bir değişiklik yapılması için verilen önerge, tadil teklifi'},],
  [{ 'word': 'HIRDAVATÇI', 'hint': 'Nalbur'},],
  [{ 'word': 'SİVRİSİNEK', 'hint': 'Çift kanatlılardan, insan ve memeli hayvanların kanıyla beslenen, birçok türü bulunan ve bir türü sıtma mikrobu aşılayan, sulak, bataklık yerlerde çok üreyen ve bulaşıcı hastalıkları yayan uçucu böcek (Culexpipiens)'},],
  [{ 'word': 'KIZILKANAT', 'hint': 'Sazangillerden, yüzgeçleri kırmızı, 25-30 santimetre boyunda, eti kılçıklı bir tatlı su balığı (Scardinus eryhrophthalmus)'},],
  [{ 'word': 'KALAYBALIK', 'hint': 'Balık avlamada oltanın ucuna yerleştirilen madde'},],
  [{ 'word': 'CİBİLLİYET', 'hint': 'Yaradılış'},],
  [{ 'word': 'KARALAHANA', 'hint': 'Yaprakları koyu yeşil olan bir tür lahana'},],
  [{ 'word': 'ÇAKARALMAZ', 'hint': 'Basit, ilkel çakmak'},],
  [{ 'word': 'ODUNPAZARI', 'hint': 'Eskişehir iline bağlı ilçelerden biri'},],
  [{ 'word': 'BAŞASİSTAN', 'hint': 'En kıdemli asistan'},],
  [{ 'word': 'ASTRONOMİK', 'hint': 'Gök bilimsel'},],
  [{ 'word': 'BAŞTANKARA', 'hint': 'Ötücü kuşlar takımının baştankaragiller familyasından, Kuzey Afrika, Avrupa ve Asya\'da yaşayan, böcek yiyerek tarıma yararlı olan, oldukça kısa, güçlü ve sivri gagalı, çeşitli renklerde olabilen bir tür kuş (Parus major)'},],
  [{ 'word': 'BEYAZSİNEK', 'hint': 'Özellikle pamukların üzerinde üreyerek bitkinin öz suyunu emen ve kurumasına sebep olan bir tür sinek'},],
  [{ 'word': 'BAŞAKŞEHİR', 'hint': 'İstanbul iline bağlı ilçelerden biri'},],
  [{ 'word': 'LASTİKOTİN', 'hint': 'İnce iplik ile çok sık dokunmuş yünlü kumaş'},],
  [{ 'word': 'KIZKAÇIRAN', 'hint': 'Fitilinin ateşlenip fırlatılmasıyla kıvılcımlar saçarak uçuşan, tiz ses çıkaran bir tür eğlence aracı'},],
  [{ 'word': 'BİLİNÇALTI', 'hint': 'Bilinç dışı olmakla birlikte, dilendiğinde kapsamındakilerin bilince çağrılabildiği zihin bölgesi, şuuraltı, tahteşşuur'},],
  [{ 'word': 'MAĞLUBİYET', 'hint': 'Yenilgi'},],
  [{ 'word': 'DİYALEKTİK', 'hint': 'Gerçekliği ve onun çelişmelerini incelemeye yarayan ve bu çelişmeleri aşmayı sağlayan yolları aramayı öngören akıl yürütme yöntemi, eytişim'},],
  [{ 'word': 'ATRAKSİYON', 'hint': 'Eğlendiri'},],
  [{ 'word': 'BAŞTANIMAZ', 'hint': 'Asi, isyancı, düzen bozucu'},],
  [{ 'word': 'DİYARBAKIR', 'hint': 'Türkiye\'nin Güneydoğu Anadolu Bölgesi\'nde yer alan illerinden biri'},],
  [{ 'word': 'YADIRGAMAK', 'hint': 'Kendine yabancı gelen bir kimseye, duruma veya şeye alışamamak, ısınamamak'},],
  [{ 'word': 'KERTENKELE', 'hint': 'Uzun vücutlu, sivri kuyruklu, çevik, böcekçil, küçük sürüngen hayvan (Lacertus)'},],
  [{ 'word': 'DERİVASYON', 'hint': 'Irmak vb.nin yatağını değiştirme'},],
  [{ 'word': 'OTOKONTROL', 'hint': 'Öz denetim'},],
  [{ 'word': 'LEKSİKOLOG', 'hint': 'Sözcük bilimci'},],
  [{ 'word': 'İKONOGRAFİ', 'hint': 'İkonların tanıtılması ve açıklanması'},],
  [{ 'word': 'ŞECERENAME', 'hint': 'Soyağacını gösteren kitap veya yazı'},],
  [{ 'word': 'ASPİDİSTRA', 'hint': 'Zambakgillerden, genellikle saksıda yetiştirilen, yaprakları doğrudan doğruya topraktan çıkan bir süs bitkisi'},],
  [{ 'word': 'İSLAMOFOBİ', 'hint': 'İslam’a veya Müslümanlara karşı beslenen korku, nefret, düşmanlık, kin vb'},],
  [{ 'word': 'CAMBAZHANE', 'hint': 'Cambazların oyunlarını gösterdikleri yer'},],
  [{ 'word': 'HASSASİYET', 'hint': 'Duyarlılık'},],
  [{ 'word': 'REDAKSİYON', 'hint': 'Yazılmış bir metin üzerinde gereken düzeltmeleri yaparak yazıyı yayıma hazır duruma getirme'},],
  [{ 'word': 'DEONTOLOJİ', 'hint': 'Ödev bilimi'},],
  [{ 'word': 'ESRARENGİZ', 'hint': 'Gizemli'},],
  [{ 'word': 'BAHÇESARAY', 'hint': 'Van iline bağlı ilçelerden biri'},],
  [{ 'word': 'DEREPAZARI', 'hint': 'Rize iline bağlı ilçelerden biri'},],
  [{ 'word': 'ÇİVİYUKARI', 'hint': 'Yağlı güreşte hasmı ayaklarından yakalayıp tepesi üstü diktikten sonra sırtını yere getirerek yenme biçimi'},],
  [{ 'word': 'ALIŞKANLIK', 'hint': 'Bir şeye alışmış olma durumu, alışkınlık, alışmışlık, alışkı, itiyat, huy, meleke, ünsiyet, yordam'},],
  [{ 'word': 'ÇEŞMİSİYAH', 'hint': 'Gözü siyah olan, kara gözlü (kimse)'},],
  [{ 'word': 'KEMOTERAPİ', 'hint': 'Kimyasal tedavi'},],
  [{ 'word': 'RADYOGRAFİ', 'hint': 'Bir organ veya cismin biçimini X ışınlarından yararlanarak görüntüleme'},],
  [{ 'word': 'ANTROPONİM', 'hint': 'Kişi adı'},],
  [{ 'word': 'RADYOSKOPİ', 'hint': 'Bir organ veya cismin her türlü açıdan biçiminin ve hareketlerinin ışınlar altında incelenmesini sağlayan muayenesi'},],
  [{ 'word': 'KOLEKSİYON', 'hint': 'Öğrenme, yarar sağlama veya zevk amacıyla bir araya getirilmiş ve özelliklerine göre sınıflara ayrılmış nesnelerin bütünü, derlem'},],
  [{ 'word': 'HİYEROGLİF', 'hint': 'Resim yazı'},],
  [{ 'word': 'YALPALAMAK', 'hint': 'Dengesi bozularak bir sağa, bir sola eğilmek'},],
  [{ 'word': 'ÇALAKIRBAÇ', 'hint': 'Şiddetli ve sürekli kırbaç vurarak'},],
  [{ 'word': 'RUHBANİYET', 'hint': 'Rahiplerin evlenmeyerek ve dünyadan el etek çekerek yaşamaları durumu'},],
  [{ 'word': 'KARNABAHAR', 'hint': 'Turpgillerden, çiçekleri etli ve tanecikli bir görünüşte olan, yaprakları lahana yaprağına benzeyen, sebze olarak kullanılan bir bitki (Brassica oleracea botrytis)'},],
  [{ 'word': 'BAŞAKORTÇU', 'hint': 'Müzik aletlerini akort edenlerin başı'},],
  [{ 'word': 'CİHANŞİNAS', 'hint': 'Dünyayı tanımış, her şeyi yerli yerinde bilen (kimse)'},],
  [{ 'word': 'VAKAYİNAME', 'hint': 'Günü gününe yazılmış olayları içine alan eser, kronik'},],
  [{ 'word': 'BERABERLİK', 'hint': 'Başa baş kalma durumu'},],
  [{ 'word': 'ONİKİTELLİ', 'hint': 'Tambura cinsinden, on iki teli olan bir halk çalgısı'},],
  [{ 'word': 'SEYDİŞEHİR', 'hint': 'Konya iline bağlı ilçelerden biri'},],
  [{ 'word': 'HALVETHANE', 'hint': 'Tekkelerde dervişlerin yalnızca ibadet etmek ve çile doldurmak için kapandıkları oda'},],
  [{ 'word': 'BIÇAKSIRTI', 'hint': 'Çok az fark, çok yakın aralık'},],
  [{ 'word': 'BİBLİYOFİL', 'hint': 'Kitapsever'},],
  [{ 'word': 'ELEKTROŞOK', 'hint': 'Ruh hastalıklarında, beyinden, kalp atışındaki düzensizliklerde göğüs duvarından çok kısa süreli yüksek elektrik akımı geçirerek hastayı iyileştirme yöntemi'},],
  [{ 'word': 'ANAFİLAKSİ', 'hint': 'Aşırı duyarlık'},],
  [{ 'word': 'DAĞITIMEVİ', 'hint': 'Dağıtım işiyle uğraşan kuruluş merkezi'},],
  [{ 'word': 'REZEKSİYON', 'hint': 'Sağlam kısımları korumak ve gerekiyorsa o kısımların bağlantısını yeniden kurmak suretiyle bir organın bir parçasını kesip çıkarmak için yapılan cerrahi müdahale'},],
  [{ 'word': 'BİBLİYOMAN', 'hint': 'Kitap düşkünü'},],
  [{ 'word': 'REDDİMİRAS', 'hint': 'Her türlü sonucuyla mirası istememe, kabul etmeme, reddetme'},],
  [{ 'word': 'DEKREŞENDO', 'hint': 'Sesi gittikçe kısarak (çalmak)'},],
  [{ 'word': 'AZLEDİLMEK', 'hint': 'Görevden alınmak'},],
  [{ 'word': 'KABUKLULAR', 'hint': 'Kabukları yapılarındaki kireçli tuzlar dolayısıyla sertleşmiş olan, solunum aygıtları balıklara benzeyen, çok hücreli hayvanlardan eklem bacaklılar sınıfı'},],
  [{ 'word': 'PASAPAROLA', 'hint': 'Bir birliğe verilen ve ağızdan ağıza bütün askerlere yayılan emir'},],
  [{ 'word': 'LORENTİYUM', 'hint': 'Atom numarası 103 olan, kaliforniyum atomlarının bor çekirdekleriyle bombardımanından elde edilen yapma element (simgesi Lr)'},],
  [{ 'word': 'İNCİRLİOVA', 'hint': 'Aydın iline bağlı ilçelerden biri'},],
  [{ 'word': 'NAKKARHANE', 'hint': 'Mehter takımı'},],
  [{ 'word': 'İMAMKAYIĞI', 'hint': 'Tabut'},],
  [{ 'word': 'BOĞAZLIYAN', 'hint': 'Yozgat iline bağlı ilçelerden biri'},],
  [{ 'word': 'DALAVERECİ', 'hint': 'Çıkarı için hileye başvuran kimse, taklacı, kolpocu, aferist'},],
  [{ 'word': 'ATIŞTIRMAK', 'hint': 'Acele olarak yemek veya içmek'},],
  [{ 'word': 'GAMMAZLAMA', 'hint': 'İspiyonlama'},],
  [{ 'word': 'REDÜKSİYON', 'hint': 'İndirgeme'},],
  [{ 'word': 'REHABİLİTE', 'hint': 'İyileştirme'},],
  [{ 'word': 'MİLLİYETÇİ', 'hint': 'Milliyet ilkesini benimseyen, milliyetsever, ulusçu, ulusalcı'},],
  [{ 'word': 'BUSBULANIK', 'hint': 'Çok bulanık'},],
  [{ 'word': 'RADİKALİZM', 'hint': 'Köktencilik'},],
  [{ 'word': 'BUHARLAŞMA', 'hint': 'Buharlaşmak işi, buğulaşma, tebahhur'},],
  [{ 'word': 'KALEMTIRAŞ', 'hint': 'Kurşun kalemlerin ucunu açmak için kullanılan türlü biçimlerdeki keski, kalem açacağı'},],
  [{ 'word': 'VAHDANİYET', 'hint': 'Tanrı\'nın birliği, bir olması'},],
  [{ 'word': 'PARAMPARÇA', 'hint': 'Pek çok parçaya ayrılmış, parça parça olmuş'},],
  [{ 'word': 'HAZIRCEVAP', 'hint': 'Gerektiğinde çabuk, yerinde cevaplar bulup veren (kimse)'},],
  [{ 'word': 'JİNEKOLOJİ', 'hint': 'Kadın hastalıkları'},],
  [{ 'word': 'HEMOGLOBİN', 'hint': 'Alyuvarların yapısında bulunan, dokulardan karbondioksidi akciğerlere, akciğerlerden oksijeni dokulara taşıyan, demir içeren ve kana kırmızı rengini veren protein'},],
  [{ 'word': 'VOLTAMETRE', 'hint': 'Bir elektrotta, açığa çıkan madde miktarına göre devreden geçen elektrik miktarını ölçmeye yarayan alet'},],
  [{ 'word': 'DENİZAŞIRI', 'hint': 'Denizlerin ötesinde bulunan'},],
  [{ 'word': 'OFTALMOLOG', 'hint': 'Göz bilimci'},],
  [{ 'word': 'YAPAYALNIZ', 'hint': 'Yanında kimse veya hiçbir şey bulunmayan (kimse)'},],
  [{ 'word': 'KIRAATHANE', 'hint': 'Kahve, kahvehane'},],
  [{ 'word': 'ISIDENETİR', 'hint': 'Bir yer veya nesnenin ısısını kendiliğinden düzenleyen, aynı derecede kalmasını sağlayan cihaz, termostat'},],
  [{ 'word': 'ASRISAADET', 'hint': 'Hz. Muhammed\'in yaşadığı zaman, saadet asrı, devrisaadet'},],
  [{ 'word': 'SAYGIDEĞER', 'hint': 'Kendisine saygı gösterilmeye değer, muhterem'},],
  [{ 'word': 'EBEBULGURU', 'hint': 'Bulgur iriliğinde yağan kar'},],
  [{ 'word': 'SÜMEROLOJİ', 'hint': 'Sümer dili ve eserlerini konu alan bilim dalı'},],
  [{ 'word': 'BAKTERİSİT', 'hint': 'Bakterikıran'},],
  [{ 'word': 'İLTİFATKAR', 'hint': 'Güler yüz gösteren, hoş davranan; mültefit'},],
  [{ 'word': 'DUMLUPINAR', 'hint': 'Kütahya iline bağlı ilçelerden biri'},],
  [{ 'word': 'DÖŞEMEALTI', 'hint': 'Antalya iline bağlı ilçelerden biri'},],
  [{ 'word': 'RESEPSİYON', 'hint': 'Kabul yeri, Kabul yerinde çalışan kimselerin tümü'},],
  [{ 'word': 'KORGENERAL', 'hint': 'Kara ve hava kuvvetlerinde rütbesi tümgeneralle orgeneral arasında olan general, ferik (II)'},],
  [{ 'word': 'ALPYILDIZI', 'hint': 'Dağların çok yüksek yamaçlarında yetişen bir çiçek (Paradisia liliastrum)'},],
  [{ 'word': 'SAFRANBOLU', 'hint': 'Karabük iline bağlı ilçelerden biri'},],
  [{ 'word': 'ADEMELMASI', 'hint': 'Erkeklerde boynun ön tarafındaki gırtlak çıkıntısı'},],
  [{ 'word': 'ORNİTORENK', 'hint': 'Gagalı memeli'},],
  [{ 'word': 'POLİKLİNİK', 'hint': 'Hastalıkların ön tanılarının ve hastaların ayakta tedavilerinin yapıldığı özel klinik'},],
  [{ 'word': 'BATTIÇIKTI', 'hint': 'Alt geçit'},],
  [{ 'word': 'ARKEOMETRİ', 'hint': 'İnsanlığın kültür tarihini anlamada arkeologlara yardımcı olabilmek için antik eserlerin ve materyallerin bilimsel yöntemlerle incelenmesi'},],
  [{ 'word': 'BUMBURUŞUK', 'hint': 'Çok, iyice buruşmuş olan'},],
  [{ 'word': 'APLİKASYON', 'hint': 'Uygulama'},],
  [{ 'word': 'KURUCAŞİLE', 'hint': 'Bartın iline bağlı ilçelerden biri'},],
  [{ 'word': 'NİMETŞİNAS', 'hint': 'Değerbilir'},],
  [{ 'word': 'AMERİKANCI', 'hint': 'Amerikancılık yanlısı olan (kimse)'},],
  [{ 'word': 'UZUNKUYRUK', 'hint': 'Bir tür iskete kuşu'},],
  [{ 'word': 'TÜBERKÜLOZ', 'hint': 'Verem'},],
  [{ 'word': 'DENİZÜZÜMÜ', 'hint': 'Yüksekliği 1-2 metre olan, dik dallı, dalları yeşil renkli, yaprakları pulsu ve kın biçiminde dalları sarmış, çalı görünüşünde, meyvesi bezelye büyüklüğünde, kırmızı ve nadiren sarı renkli, çok yıllık bir bitki (Ephedromajor)'},],
  [{ 'word': 'BAYRAMÖREN', 'hint': 'Çankırı iline bağlı ilçelerden biri'},],
  [{ 'word': 'BAĞDALAMAK', 'hint': 'Düşürmek için ayağını birinin ayaklarına takmak, çelme atmak'},],
  [{ 'word': 'KENARORTAY', 'hint': 'Bir üçgende her tepeden karşı kenarın ortasına indirilen doğru parçası'},],
  [{ 'word': 'TOPRAKKALE', 'hint': 'Osmaniye iline bağlı ilçelerden biri'},],
  [{ 'word': 'DOMUZAYAĞI', 'hint': 'Tüfek namlusundan sıkıyı çıkarmaya yarar çengelli çubuk'},],
  [{ 'word': 'BİYOENERJİ', 'hint': 'Biyokütlenin kimyasal dönüşümüyle elde edilen enerji'},],
  [{ 'word': 'DENSİMETRE', 'hint': 'Bitkilerin dış kısımları ile toprak üzerinde kapladıkları alanı çeşitli büyüklüklerdeki halkalar yardımı ile ölçen bir alet'},],
  [{ 'word': 'ÇARKIFELEK', 'hint': 'Yakıldığında dönerek kıvılcım saçan donanma fişeği'},],
  [{ 'word': 'GEREKSİNİM', 'hint': 'Eksikliği duyulan şey, ihtiyaç'},],
  [{ 'word': 'BOYUNDURUK', 'hint': 'Çift süren veya arabaya koşulan hayvanların birlikte yürümelerini sağlamak için boyunlarına geçirilen bir tür ağaç çember'},],
  [{ 'word': 'AKINKAYASI', 'hint': 'Kaya balığıgiller familyasından derin ve uzaklarda yaşayan ince, uzun bir tür balık'},],
  [{ 'word': 'ÇÖZÜNÜRLÜK', 'hint': 'Bir maddenin başka bir madde içinde çözünme özelliği, resolüsyon'},],
  [{ 'word': 'ANTARKTİKA', 'hint': 'Güney yarım kürenin en güneyinde olan Güney Kutbu\'nu ve etrafını içine alan, üzerinde herhangi bir ülke bulunmayan kıta'},],
  [{ 'word': 'BÖCEKKAPAN', 'hint': 'Örnek bitkisi drosera olan ve bazı organları böcek yakalamaya, sindirmeye elverişli olan bitkilerin ortak adı'},],
  [{ 'word': 'EKONOMETRİ', 'hint': 'Ekonomik olayların açıklanmasında çok sayıda değişkeni göz önüne alarak ve karşılıklı bağıntılar kurarak teorik çalışmaların deneylerle doğrulanmasını sağlayan matematiksel yöntem'},],
  [{ 'word': 'DARÜLFÜNUN', 'hint': 'Üniversite'},],
  [{ 'word': 'PERPERİŞAN', 'hint': 'Çok kötü bir durumda'},],
  [{ 'word': 'ATARAKSİYA', 'hint': 'Hiçbir heyecan veya zihin etkisiyle uyarılmayan ruh dinginliği, acıya olduğu kadar kıvanca karşı da ilgisizlik'},],
  [{ 'word': 'ÇEŞİTKENAR', 'hint': 'Kenarlarından hiçbiri ötekine eşit olmayan (çokgen)'},],
  [{ 'word': 'SICAKKANLI', 'hint': 'Sevimli, cana yakın, sempatik'},],
  [{ 'word': 'HAVALİMANI', 'hint': 'Uluslararası veya şehirler arası hava yolu ulaşımı için gerekli teknik ve ticari kuruluşların bütünü'},],
  [{ 'word': 'ZORUNLULUK', 'hint': 'Olması gerekme, olduğundan başka olmama, zorunlu olma, mecburluk, mecburiyet, mecburilik, zaruret, ıztırar, zorunluk, zarurilik'},],
  [{ 'word': 'YASTIKALTI', 'hint': 'Banka veya bir başka yere yatırılmak yerine evde, iş yerinde saklanan taşınabilir (değer)'},],
  [{ 'word': 'ATMOSFERİK', 'hint': 'Atmosferle ilgili, cevvi'},],
  [{ 'word': 'ALKOLMETRE', 'hint': 'Alkolölçer'},],
  [{ 'word': 'ADAYAVRUSU', 'hint': 'İki veya üç çifte kürekli küçük balıkçı teknesi'},],
  [{ 'word': 'KARAKILÇIK', 'hint': 'Kılçıkları siyah olan, kırmızı veya beyaz, sert taneli buğday'},],
  [{ 'word': 'ÇAMAŞIRLIK', 'hint': 'Çamaşır yıkamak için kullanılan yer, çamaşırhane'},],
  [{ 'word': 'KIZILGEYİK', 'hint': 'Geyikgillerden, Avrupa ve Asya\'nın ılık bölgelerindeki ağaçlık yerlerde yaşayan, rengi kırmızımsı, uzunluğu yaklaşık 2 metre olan bir tür geyik (Cerves elaphus)'},],
  [{ 'word': 'ABEROMETRE', 'hint': 'Hassas denetim ve gözlemlerde hataları ölçmekte kullanılan aygıt'},],
  [{ 'word': 'KIRKLARELİ', 'hint': 'Türkiye\'nin Marmara Bölgesi\'nde yer alan illerinden biri'},],
  [{ 'word': 'İĞNEDANLIK', 'hint': 'İğnelik'},],
  [{ 'word': 'BEYLİKDÜZÜ', 'hint': 'İstanbul iline bağlı ilçelerden biri'},],
  [{ 'word': 'PROSPEKTÜS', 'hint': 'Reçeteli veya reçetesiz ilaçlar hakkında hastaya gerekli bilgileri sağlayan belge'},],
  [{ 'word': 'ANJANBUMAN', 'hint': 'Dizenin son kelimesiyle sonraki dizeyi başlatma sanatı'},],
  [{ 'word': 'HELENİSTİK', 'hint': 'Helen kültürüne, tarihine, diline ve edebiyatına ait olan'},],
  [{ 'word': 'CUMHURİYET', 'hint': 'Milletin, egemenliği kendi elinde tuttuğu ve bunu belirli süreler için seçtiği milletvekilleri aracılığıyla kullandığı yönetim biçimi'},],
  [{ 'word': 'ZEVKİSELİM', 'hint': 'En yüksek zevk'},],
  [{ 'word': 'BAKADURMAK', 'hint': 'Bakma işini sürdürmek'},],
  [{ 'word': 'HALKAPINAR', 'hint': 'Konya iline bağlı ilçelerden biri'},],
  [{ 'word': 'KANSEROJEN', 'hint': 'Kanser yapıcı'},],
  [{ 'word': 'DARÜLACEZE', 'hint': 'Düşkünlerevi'},],
  [{ 'word': 'ANAHTARLIK', 'hint': 'Anahtarların kaybolmasını önlemek ve kolayca kullanılmasını sağlamak için takıldığı maden, deri vb.nden yapılan halka veya kılıf'},],
  [{ 'word': 'İSKANDİNAV', 'hint': 'İsveç, Norveç, Danimarka ve Finlandiya’da yaşayan halk veya bu halkın soyundan olan kimse'},],
  [{ 'word': 'ARSIULUSAL', 'hint': 'Uluslararası'},],
  [{ 'word': 'BİLGİSAYAR', 'hint': 'Çok sayıda aritmetiksel veya mantıksal işlemlerden oluşan bir işi, önceden verilmiş bir programa göre yapıp sonuçlandıran elektronik araç, elektronik beyin'},],
  [{ 'word': 'AZİMKARANE', 'hint': 'Kararlılıkla, kararlı olarak'},],
  [{ 'word': 'ANABOLİZMA', 'hint': 'Özümleme'},],
  [{ 'word': 'ŞEHİTKAMİL', 'hint': 'Gaziantep iline bağlı ilçelerden biri'},],
  [{ 'word': 'BİRİNCASIF', 'hint': 'Birleşikgillerden, hekimlikte kullanılan bir bitki'},],
  [{ 'word': 'DALGAÖLÇER', 'hint': 'Oluşan dalgaların yüksekliğini ve derinliğini ölçen alet'},],
  [{ 'word': 'BAYRAMPAŞA', 'hint': 'İstanbul iline bağlı ilçelerden biri'},],
  [{ 'word': 'GÖĞÜSLEMEK', 'hint': 'Karşı durmak, engel olmak, direnmek'},],
  [{ 'word': 'RADYOMETRE', 'hint': 'Işınölçer'},],
  [{ 'word': 'BÜYÜKPEDER', 'hint': 'Büyükbaba, dede'},],
  [{ 'word': 'ALTINBEŞİK', 'hint': 'Bir eliyle kendi bileklerini kavrayan iki kişinin, öteki eliyle karşılıklı olarak birbirlerinin bileklerini tutmaları'},],
  [{ 'word': 'DİKDÖRTGEN', 'hint': 'Açıları dik olan paralel kenar, mustatil'},],
  [{ 'word': 'KEÇİMEMESİ', 'hint': 'Sert kabuklu, iri taneli, uzunca, beyaz veya kırmızımsı bir tür üzüm'},],
  [{ 'word': 'AKTİVASYON', 'hint': 'Etkinleştirme'},],
  [{ 'word': 'BELEŞÇİLİK', 'hint': 'Bedavacılık'},],
  [{ 'word': 'OLAĞANÜSTÜ', 'hint': 'Alışılmıştan, benzerlerinden farklı olan, fevkalade'},],
  [{ 'word': 'TAKSİMETRE', 'hint': 'Taksilerde ödenecek ücreti gösteren sayaç'},],
  [{ 'word': 'TAVŞANAĞZI', 'hint': 'Pembe renkli bir tür çiçek'},],
  [{ 'word': 'NÜMİSMATİK', 'hint': 'Eski para ve madalyaların tarihi ve tanımıyla uğraşan bilim'},],
  [{ 'word': 'KAMIŞKULAK', 'hint': 'Kulakları ince, düzgün ve dik at'},],
  [{ 'word': 'BÖCEKSAVAR', 'hint': 'Evdeki zararlı böcekleri savıp öldürmekte kullanılan ve ilaç püskürten araç'},],
  [{ 'word': 'PAZARLAMAK', 'hint': 'Bir ürünü, bir malı, bir hizmeti satacak uygun piyasa bulmak'},],
  [{ 'word': 'MOTOSİKLET', 'hint': 'Motor silindirinin hacmi 125 santimetreküpten büyük olan, iki tekerlekli motorlu taşıt, motor'},],
  [{ 'word': 'TRANSKRİPT', 'hint': 'Not döküm belgesi'},],
  [{ 'word': 'BÜYÜKORHAN', 'hint': 'Bursa iline bağlı ilçelerden biri'},],
  [{ 'word': 'FOTOKİNEZİ', 'hint': 'Bazı hayvanları karanlıkta ışık, çok aydınlıkta ise karanlık aramaya iteleyen dürtü'},],
  [{ 'word': 'DİŞİNDİRİK', 'hint': 'İpe ilmik atarak hayvanın ağzına takılan gem'},],
  [{ 'word': 'MANYETİZMA', 'hint': 'Mıknatıs özelliklerinin bütünü'},],
  [{ 'word': 'DEVRİKEBİR', 'hint': 'Türk müziğinde bir büyük usul'},],
  [{ 'word': 'DEVELOPMAN', 'hint': 'Fotoğrafçılıkta kullanılan, kimyevi bir tür banyo maddesi'},],
  [{ 'word': 'FEDERALİZM', 'hint': 'Birçok devletin özel yasalara ve bağımsızlığa sahip olarak tek bir devlet durumunda birleşmeleri yöntemi'},],
  [{ 'word': 'TERMOMETRE', 'hint': 'Sıcaklıkölçer'},],
  [{ 'word': 'DOLAMBAÇLI', 'hint': 'İçinden zor çıkılır, çapraşık'},],
  [{ 'word': 'FOTOSENTEZ', 'hint': 'Yeşil bitkilerin ışıkta basit birleşiklerinden karmaşık yapılı organik moleküller üretmesi'},],
  [{ 'word': 'DOKUMAHANE', 'hint': 'Dokuma tezgâhlarının bulunduğu ve çalıştığı yer'},],
  [{ 'word': 'KARAKALPAK', 'hint': 'Özbekistan Cumhuriyeti’ne bağlı Karakalpakistan Özerk Cumhuriyeti’nde yaşayan Türk halkı ve bu halkın soyundan olan kimse'},],
  [{ 'word': 'CANCAĞIZIM', 'hint': 'Yakın birisi için kullanılan bir sevgi sözü'},],
  [{ 'word': 'ENDOTERMİK', 'hint': 'Isıalan'},],
  [{ 'word': 'NAMAZBOZAN', 'hint': 'Bir tür eğrelti otu'},],
  [{ 'word': 'BİKARBONAT', 'hint': 'Hidrojen karbonatların genel adı'},],
  [{ 'word': 'RÜZGARGÜLÜ', 'hint': 'Rüzgârların yönünü ve adını gösteren levha'},],
  [{ 'word': 'RUHSATNAME', 'hint': 'Belli etkinliklerde bulunabilmek, kamu hizmet ve mallarından yararlanabilmek için kişilere, önceden belirlenmiş bazı şartlara uyma kaydıyla idarece verilen izin, ruhsat'},],
  [{ 'word': 'BETONKARAR', 'hint': 'Beton yapmak üzere çimento, kum ve suyu karıştıran makine, betoniyer'},],
  [{ 'word': 'TRAJİKOMİK', 'hint': 'Hem acıklı hem de güldürücü özelliği olan'},],
  [{ 'word': 'LİBERALİZM', 'hint': 'Serbestlik, Erkincilik'},],
  [{ 'word': 'BİLGİYAZAR', 'hint': 'Elektronik sistemle dizgi yapan alet'},],
  [{ 'word': 'TELEVİZYON', 'hint': 'Vericiden iletilen dalgaların görüntü ve ses olarak görünmesini ve duyulmasını sağlayan aygıt'},],
  [{ 'word': 'TAHTALIKÖY', 'hint': 'Mezarlık'},],
  [{ 'word': 'ÇAPAÇULLUK', 'hint': 'Çapaçul olma durumu, kılık kıyafete özen göstermeyiş'},],
  [{ 'word': 'ESKALASYON', 'hint': 'İhalelerde sözleşme fiyatının maliyetlerdeki artışa göre güncellenmesi'},],
  [{ 'word': 'PROVOKATÖR', 'hint': 'Kışkırtmacı'},],
  [{ 'word': 'GÜÇLÜKONAK', 'hint': 'Şırnak iline bağlı ilçelerden biri'},],
  [{ 'word': 'MİTOKONDRİ', 'hint': 'Hücrede enerji üretiminden sorumlu olan ve oksijenli solunumun gerçekleştiği organcık'},],
  [{ 'word': 'FİZİBİLİTE', 'hint': 'Yapılabilirlik'},],
  [{ 'word': 'DİSPROSYUM', 'hint': 'Atom numarası 66, atom ağırlığı 162,5, yoğunluğu 8,54 olan, 1500 °C\'de eriyen, açık yeşil renkte çözeltiler veren, az bulunan bir element (simgesi Dy)'},],
  [{ 'word': 'FAREKULAĞI', 'hint': 'Çuha çiçeğigillerden, tohumu kuş yemi olarak kullanılan bitkilerin cins adı, bağırsak otu, sıçankulağı (Anagallis)'},],
  [{ 'word': 'PEMBEGEMRE', 'hint': 'Genellikle Akdeniz ve Ege bölgelerinde yetişen, taneleri iri, kalın kabuklu, salkımı konik biçimde olan bir tür üzüm'},],
  [{ 'word': 'İKTİDARSIZ', 'hint': 'Gücü, yeteneği olmayan, beceriksiz, yetersiz'},],
  [{ 'word': 'PERİBACASI', 'hint': 'Kolayca aşınabilen taş ve kayalardan oluşmuş, sivri kule veya piramit görünüşlü, kiminin tepesinde külah veya tepsiyi andıran bir kaya parçası bulunan yeryüzü biçimi'},],
  [{ 'word': 'İSTATİSTİK', 'hint': 'İlkelerini olasılık kuramlarından alarak eldeki verileri grafik ve sayı biçiminde değerlendirmeye dayandıran matematiğin uygulamalı dalı, sayım bilimi'},],
  [{ 'word': 'TOPUKDÖVEN', 'hint': 'Etekleri yere kadar uzanan kadın giysisi'},],
  [{ 'word': 'ÇAKOZLAMAK', 'hint': 'Uygunsuz bir durumu fark etmek'},],
  [{ 'word': 'BAĞLAŞIMLI', 'hint': 'Aralarında karşılıklı destek ve bağımlılık bulunan'},],
  [{ 'word': 'DOLUDİZGİN', 'hint': 'Son hızla, çok hızlı bir biçimde'},],
  [{ 'word': 'BAŞÇİFTLİK', 'hint': 'Tokat iline bağlı ilçelerden biri'},],
  [{ 'word': 'ANTROPOLOG', 'hint': 'İnsan bilimi uzmanı, insan bilimci'},],
  [{ 'word': 'ENTOMOLOJİ', 'hint': 'Böcek bilimi'},],
  [{ 'word': 'SERİNHİSAR', 'hint': 'Denizli iline bağlı ilçelerden biri'},],
  [{ 'word': 'KAYINPEDER', 'hint': 'Kaynata'},],
  [{ 'word': 'ORDİNARYÜS', 'hint': 'Türk üniversitelerinde 1960 öncesinde, en az beş yıl profesörlük yapmış, bilimsel çalışmalarıyla kendini tanıtmış öğretim üyeleri arasından seçilerek bir kürsünün yönetimiyle görevlendirilen kimselere verilen unvan'},],
  [{ 'word': 'AMPERMETRE', 'hint': 'Akımölçer'},],
  [{ 'word': 'AKIMTOPLAR', 'hint': 'Akümülatör'},],
  [{ 'word': 'GÜRGENTEPE', 'hint': 'Ordu iline bağlı ilçelerden biri'},],
  [{ 'word': 'YANARDÖNER', 'hint': 'Daldan dala atlanan, konudan konuya geçilen'},],
  [{ 'word': 'ALTIKARDEŞ', 'hint': 'Kuzey Kutbu yönünde, Büyükayı\'nın karşısında bulunan takımyıldız; Zatülkürsi'},],
  [{ 'word': 'BATTALGAZİ', 'hint': 'Malatya iline bağlı ilçelerden biri'},],
  [{ 'word': 'DELEGASYON', 'hint': 'Herhangi bir topluluğu temsil etmekle görevli yetkili kurul'},],
  [{ 'word': 'CİĞERDELDİ', 'hint': 'Kumaş üzerine küçük delikler açılarak yapılan işleme'},],
  [{ 'word': 'KONJONKTÜR', 'hint': 'Her türlü durum ve şartın ortaya çıkardığı sonuç, geçerli durum'},],
  [{ 'word': 'PORTEKİZCE', 'hint': 'Portekiz’de ve Portekizlilerin hâkim olduğu bölgelerde yaşayanlar tarafından kullanılan dil'},],
  [{ 'word': 'ÇOBANÜZÜMÜ', 'hint': 'Yaban mersini'},],
  [{ 'word': 'AŞIKTAŞLIK', 'hint': 'Aralarında ciddi bir sevgi olmadan birbirleriyle gönül eğlendirme; muaşaka'},],
  [{ 'word': 'DEREBEYLİK', 'hint': 'Orta Çağda özellikle Batı Avrupa\'da toprağı ve üzerinde yaşayan köylüleri tek bir kimsenin malı sayan siyasal düzen, feodalite'},],
  [{ 'word': 'DOĞANŞEHİR', 'hint': 'Malatya iline bağlı ilçelerden biri'},],
  [{ 'word': 'KALITIMSAL', 'hint': 'Soydan geçme, soydan kalma, kalıtımla ilgili, kalıtsal, irsî'},],
  [{ 'word': 'PROPAGANDA', 'hint': 'Bir öğreti, düşünce veya inancı başkalarına tanıtmak, benimsetmek ve yaymak amacıyla söz, yazı vb. yollarla gerçekleştirilen çalışma, yaymaca'},],
  [{ 'word': 'SAPASAĞLAM', 'hint': 'Çok sağlam, her yanı sağlam'},],
  [{ 'word': 'ASİSTANLIK', 'hint': 'Asistan, araştırma görevlisi olma durumu'},],
  [{ 'word': 'ADAMAKILLI', 'hint': 'Gereğinden çok, iyice, bir güzel, bir temiz'},],
  [{ 'word': 'ALFATERAPİ', 'hint': 'Alfa ışınları kullanılarak yapılan tedavi'},],
  [{ 'word': 'ALTERNATÖR', 'hint': 'Dalgalı akım üreteci'},],
  [{ 'word': 'ÇÖPATLAMAZ', 'hint': 'Gözünden hiçbir şey kaçmayacak kadar titiz ve dikkatli olan, aldatılamaz'},],
  [{ 'word': 'BALKANOLOG', 'hint': 'Balkanoloji uzmanı'},],
  [{ 'word': 'HAYATAĞACI', 'hint': 'Soyağacı'},],
  [{ 'word': 'DEVETABANI', 'hint': 'Birleşikgillerden, geniş yapraklı bir süs bitkisi (Phlodentron)'},],
  [{ 'word': 'BAŞAĞIRLIK', 'hint': 'Ağır sıklet'},],
  [{ 'word': 'KARTPOSTAL', 'hint': 'Genellikle dikdörtgen biçiminde ince kartondan yapılmış, bir yüzü resimli, zarflı veya zarfsız gönderilen posta kartı, kart'},],
  [{ 'word': 'GÖMÜLDÜRÜK', 'hint': 'Eyerin geriye kaymaması için atların boyunlarından aşırılıp kolanlarına bağlanan kayış'},],
  [{ 'word': 'GARİPSEMEK', 'hint': 'Bir şeyi garip, tuhaf ve uygunsuz bulmak, alışamamak, yadırgamak'},],
  [{ 'word': 'ELEKTROLİZ', 'hint': 'Bir elektrik akımının etkisiyle ortaya çıkan kimyasal ayrışma'},],
  [{ 'word': 'BAKAKALMAK', 'hint': 'Şaşkınlığa uğrayıp ne yapacağını bilmez durumda kalmak'},],
  [{ 'word': 'TUĞGENERAL', 'hint': 'Kara ve hava kuvvetlerinde, rütbesi albay ile tümgeneral arasında bulunan general, liva, mirliva'},],
  [{ 'word': 'LİMNOLOJİK', 'hint': 'Göl bilimsel'},],
  [{ 'word': 'MEVZUBAHİS', 'hint': 'Söz konusu'},],
  [{ 'word': 'ANALIKIZLI', 'hint': 'Yuvalama'},],
  [{ 'word': 'MÜZİKALİTE', 'hint': 'Müziğe uygun özellikleri taşıma'},],
  [{ 'word': 'ASHABIKEHF', 'hint': 'Yedi Uyurlar'},],
  [{ 'word': 'TÜMGENERAL', 'hint': 'Kara ve hava kuvvetlerinde, rütbesi tuğgeneralle korgeneral arasında bulunan general, ferik (II)'},],
  [{ 'word': 'ANEMOMETRE', 'hint': 'Yelölçer'},],
  [{ 'word': 'İLKÖĞRETİM', 'hint': 'Birkaç öğretim basamağından oluşan örgün eğitim sisteminin temel bilgi ve becerileri kazandıran sekiz yıllık ilk basamağı, ilköğrenim, zorunlu öğrenim'},],
  [{ 'word': 'DAĞDAĞASIZ', 'hint': 'Gürültüsüz, patırtısız, sessiz ve sakin'},],
  [{ 'word': 'DANSİMETRE', 'hint': 'Yoğunlukölçer'},],
  [{ 'word': 'ÇEMİŞGEZEK', 'hint': 'Tunceli iline bağlı ilçelerden biri'},],
  [{ 'word': 'İSTİFANAME', 'hint': 'Bir görevden kendi isteğiyle ayrıldığını belirten dilekçe, istifa'},],
  [{ 'word': 'AVUNDURMAK', 'hint': 'Oyalanmasını sağlamak'},],
  [{ 'word': 'ŞÖMENTABLA', 'hint': 'Sehpa veya yemek masasının kendi boyutundan küçük olup üzerlerine örtülen, el işinden veya kumaştan yapılmış örtü'},],
  [{ 'word': 'İSTİHBARAT', 'hint': 'Bilgi toplama, haber alma, Yeni öğrenilen bilgiler, haberler, duyumlar'},],
  [{ 'word': 'AŞINDIRICI', 'hint': 'Madenleri elektriksel, kimyasal veya mekanik yollarla aşındıran, korozif'},],
  [{ 'word': 'ÇEKOSLOVAK', 'hint': 'Çekoslovakya\'da yaşayan kimse'},],
  [{ 'word': 'PERFORMANS', 'hint': 'Başarım'},],
  [{ 'word': 'FÜZYOMETRE', 'hint': 'Erime ısısını ölçmeye yarayan cihaz'},],
  [{ 'word': 'ÇİÇEKSİMEK', 'hint': 'Çiçek gibi olmak, çiçeklenmek'},],
  [{ 'word': 'MELANKOLİK', 'hint': 'Hüzün veren, hüzün belirtisi olan'},],
  [{ 'word': 'KAHVERENGİ', 'hint': 'Kavrulmuş kahvenin rengi'},],
  [{ 'word': 'MOTİVASYON', 'hint': 'İsteklendirme, Güdüleme'},],
  [{ 'word': 'ALİYYÜLALA', 'hint': 'En güzel, en iyi, mükemmel olan'},],
  [{ 'word': 'PARALİMPİK', 'hint': 'Çeşitli dallarda bireysel veya takım hâlinde engelli sporcular tarafından oynanan (yarışma)'},],
  [{ 'word': 'İMALATHANE', 'hint': 'Ham maddeleri işleyerek piyasaya çıkacak duruma getiren iş yeri, yapımevi'},],
  [{ 'word': 'DEZENFEKTE', 'hint': 'Mikroplardan temizlenmiş'},],
  [{ 'word': 'ALTERNATİF', 'hint': 'Seçenek, Değişik, farklı'},],
  [{ 'word': 'DENİZANASI', 'hint': 'Sölenterlerden, yassı bir diske benzeyen, saydam, serbestçe yüzebilen deniz hayvanı, medüz'},],
  [{ 'word': 'KARDİYOLOG', 'hint': 'Kalp hastalıklarında uzmanlaşmış hekim'},],
  [{ 'word': 'BAĞIMLILIK', 'hint': 'Bağımlı olma durumu, tabiiyet'},],
  [{ 'word': 'GÜNÜBİRLİK', 'hint': 'Bütün bir gün boyunca, gece kalmadan yapılan'},],
  [{ 'word': 'EYÜPSULTAN', 'hint': 'İstanbul iline bağlı ilçelerden biri'},],
  [{ 'word': 'BÜROKRATİK', 'hint': 'Kamu yönetimi ile ilgili'},],
  [{ 'word': 'KORELASYON', 'hint': 'Bağıntı'},],
  [{ 'word': 'ASTROPİKAL', 'hint': 'Tropikal bölgelere yakın fakat daha yüksek bir enlemde olan'},],
  [{ 'word': 'KARAMÜRSEL', 'hint': 'Kocaeli iline bağlı ilçelerden biri'},],
  [{ 'word': 'SİSTEMATİK', 'hint': 'Sistemli'},],
  [{ 'word': 'GADOLİNYUM', 'hint': 'Atom numarası 64, atom ağırlığı 156,9 olan, yüksek ısıda eriyen, birtakım tuzları bilinen, parlak gri renkte katı element (simgesi Gd)'},],
  [{ 'word': 'ÇİNKOGRAFİ', 'hint': 'Çoğaltılmak istenilen resim veya yazıların kalıbını çinko üzerine çıkarma sanatı'},],
  [{ 'word': 'BEREKETSİZ', 'hint': 'Kendinden beklenen yararlığı sağlayamayan'},],
  [{ 'word': 'ARİSTOKRAT', 'hint': 'Soylu'},],
  [{ 'word': 'ONTOLOJİZM', 'hint': 'Tanrı bilgisinin insan için doğal olduğunu ileri süren kuram'},],
  [{ 'word': 'GRAFOMETRE', 'hint': 'Planların yapımında, arazi üzerindeki açıları ölçmekte kullanılan araç'},],
  [{ 'word': 'BEYAZTİLKİ', 'hint': 'Tilkinin kışlık tüyünden yapılan kürk'},],
  [{ 'word': 'ÜZÜMGÜNEŞİ', 'hint': 'İnce uzun gövdeli, ön kanatlı ve ince duyargalı küçük kelebek'},],
  [{ 'word': 'PAŞAÇADIRI', 'hint': 'Begonyagillerden, kalp biçimindeki yapraklarının altı kırmızımtırak, üstü koyu yeşil, gövdesi sürünücü ve etli bir süs bitkisi (Begonia feasti)'},],
  [{ 'word': 'DOĞANHİSAR', 'hint': 'Konya iline bağlı ilçelerden biri'},],
  [{ 'word': 'DEMİRPERDE', 'hint': 'İkinci Dünya Savaşı sonrası soğuk savaş döneminde, Batılı ülkelerin kendilerini Doğu Bloku ülkelerinden ayıran sınıra ve bu ülkelere taktıkları ad'},],
  [{ 'word': 'KEÇİSAKALI', 'hint': 'Gülgillerden, beyaz veya pembe çiçekli, bahçelerde süs bitkisi olarak yetiştirilen bir ağaççık, erkeçsakalı, çayırmelikesi (Spiraea aruncus)'},],
  [{ 'word': 'AMPÜTASYON', 'hint': 'Kol, bacak, kulak gibi organların tedavi amacıyla kısmen veya tamamen kesilip çıkartılması'},],
  [{ 'word': 'UĞURSUZLUK', 'hint': 'Bazı olaylarda görülen ve insana kötülük getirdiğine inanılan belirti veya bazı nesnelerde var olduğuna inanılan güç, kademsizlik, meymenetsizlik, nuhuset, şeamet, şomluk'},],
  [{ 'word': 'ZEYTİNYAĞI', 'hint': 'Zeytin tanelerinden çıkarılan bitkisel yağ'},],
  [{ 'word': 'PSİKİYATRİ', 'hint': 'Ruh ve sinir hastalıklarıyla, kişide görülen önemli uyumsuzlukları önleme, teşhis ve tedavi etmeyle uğraşan uzmanlık dalı'},],
  [{ 'word': 'FİNCANDİBİ', 'hint': 'Arazi koşulları nedeniyle inilmesi zor olan, çukurda kalan havaalanı'},],
  [{ 'word': 'VİRDİZEBAN', 'hint': 'Dile dolama, dilden düşürmeme'},],
  [{ 'word': 'HARİKULADE', 'hint': 'Eşi görülmemiş, şaşkınlık yaratıcı, olağanüstü'},],
  [{ 'word': 'HAYSİYETLİ', 'hint': 'Değeri, saygınlığı olan, onurlu'},],
  [{ 'word': 'DOGMACILIK', 'hint': 'Öne sürülen öğreti ve ilkeleri eleştirmeden doğru olarak benimseyen ve benimsediği varsayımlardan katı bir yöntemle önermeler türeten anlayış, dogmatizm'},],
  [{ 'word': 'AKBALIKÇIL', 'hint': 'Leyleksilerden, bataklık, ırmak ve göl kıyılarında yaşayan, oldukça büyük, ak renkli bir tür kuş (Egretta alba)'},],
  [{ 'word': 'ÇAKALBOĞAN', 'hint': 'Kırlarda rastlanan bir bitki'},],
  [{ 'word': 'RADYOAKTİF', 'hint': 'Işın etkin'},],
  [{ 'word': 'DEZAVANTAJ', 'hint': 'Avantajlı olmama durumu'},],
  [{ 'word': 'PANTÜRKİZM', 'hint': 'Türkçülük'},],
  [{ 'word': 'MEKATRONİK', 'hint': 'Mekanik, elektrik, elektronik ve bilgisayar sistemlerinin bir arada bulunduğu disiplin biçimi'},],
  [{ 'word': 'ADAPTASYON', 'hint': 'Uyarlama'},],
  [{ 'word': 'ARKEOLOJİK', 'hint': 'Kazı bilimsel'},],
  [{ 'word': 'BASMAKALIP', 'hint': 'Özgünlüğü olmayan, değişiklik göstermeyen, bilineni tekrarlayan, harcıâlem, klişe'},],
  [{ 'word': 'BASTIBACAK', 'hint': 'Bacakları kısa veya çarpık (kimse)'},],
  [{ 'word': 'PRAGMATİZM', 'hint': 'Yararcılık'},],
  [{ 'word': 'KARNIYARIK', 'hint': 'Uzunlamasına yarılan kızarmış patlıcanların ortasına kıymalı iç konularak hazırlanmış yemek'},],
  [{ 'word': 'LAFAZANLIK', 'hint': 'Gevezelik'},],
  [{ 'word': 'KABATASLAK', 'hint': 'Bir şeyin ayrıntılarına girmeden ana çizgilerini belirten'},],
  [{ 'word': 'İCAZETNAME', 'hint': 'İzin belgesi, onay belgesi, diploma'},],
  [{ 'word': 'İBADETHANE', 'hint': 'Tapınak'},],
  [{ 'word': 'KEDİGİLLER', 'hint': 'Kedi, aslan, kaplan, pars vb. hayvanları içine alan etçil memeli hayvanlar sınıfı'},],
  [{ 'word': 'HATIRŞİNAS', 'hint': 'Saygılı, hatır sayan, hatır kırmayan'},],
  [{ 'word': 'GELENEKSEL', 'hint': 'Geleneğe dayanan, gelenekle ilgili olan, kökleşik, ananevi, tradisyonel'},],
  [{ 'word': 'ROMANOLOJİ', 'hint': 'Romen dilleri bilimi'},],
  [{ 'word': 'BAŞSAĞLIĞI', 'hint': 'Ölen bir kimsenin yakınlarına ilgi ve yakınlık gösterme'},],
  [{ 'word': 'BAĞLILAŞIK', 'hint': 'Biri ötekine bağlı olarak var olan, biri olmadan öteki düşünülemeyen iki şeyin bu ilişki yönünden durumu'},],
  [{ 'word': 'METEOROLOG', 'hint': 'Hava tahmincisi'},],
  [{ 'word': 'BÜYÜKŞEHİR', 'hint': 'Merkezî idarenin vali yönetimindeki şehirlerinden nüfus ve ticaret bakımından belli bir büyüklükte olanı, megakent, megapol'},],
  [{ 'word': 'ENTÜBASYON', 'hint': 'Hastanın herhangi bir vücut kanalına veya boşluğuna özellikle solunum yoluna tüp yerleştirilmesi işlemi'},],
  [{ 'word': 'CEVVALİYET', 'hint': 'Çabukluk, hareketlilik'},],
  [{ 'word': 'LEJİTİMİST', 'hint': 'Meşrutiyetçi'},],
  [{ 'word': 'LENGÜİSTİK', 'hint': 'Dil bilimi'},],
  [{ 'word': 'BESTENİGAR', 'hint': 'Klasik Türk müziğinde en eski birleşik makamlardan biri'},],
  [{ 'word': 'POPÜLASYON', 'hint': 'nüfus, varlık'},],
  [{ 'word': 'VEJETARYEN', 'hint': 'Yalnız bitkisel gıda maddelerine yer veren beslenme rejimi, etyemez'},],
  [{ 'word': 'GASTRONOMİ', 'hint': 'Sağlığa uygun, iyi düzenlenmiş, hoş ve lezzetli mutfak, yemek düzeni ve sistemi'},],
  [{ 'word': 'BEYAZLATMA', 'hint': 'Beyazlatmak işi, ağartma'},],
  [{ 'word': 'AKROMEGALİ', 'hint': 'Genel gelişme bittikten sonra el, çene, burun vb. vücudun sivri kısımlarındaki kemiklerin kalınlaşması, büyümesi veya uzaması'},],
  [{ 'word': 'KEPÇEBURUN', 'hint': 'Bir tür yaban ördeği'},],
  [{ 'word': 'BREZİLYALI', 'hint': 'Brezilya’da yaşayan halk veya bu halkın soyundan olan kimse'},],
  [{ 'word': 'GÖSTERİŞÇİ', 'hint': 'Gösteriş yapmasını seven, gösteriş amacı güden kimse'},],
  [{ 'word': 'SARBANBAŞI', 'hint': 'Padişahların develerine bakan devecilerin başı'},],
  [{ 'word': 'KALBURÜSTÜ', 'hint': 'Seçkin, sivrilmiş, önde gelen'},],
  [{ 'word': 'ELEKTRONİK', 'hint': 'Serbest elektronların etkisiyle oluşan olayları inceleyen bilim dalı'},],
  [{ 'word': 'ALTIPATLAR', 'hint': 'Fişek koymaya yarayan bölümü silindir biçiminde ve namlu gerisinde olan, tek parçadan oluşmuş, altı tane fişek alan tabanca, revolver'},],
  [{ 'word': 'İNDÜKLEMEK', 'hint': 'Kapalı bir devreyi, şiddeti her an değişen bir manyetik alanın içine koyarak onun üzerinde bir elektrik akımı oluşturmak'},],
  [{ 'word': 'BEYİNORAĞI', 'hint': 'Beynin iki lobu arasındaki zar'},],
  [{ 'word': 'NATÜRALİST', 'hint': 'Natüralizm akımını benimseyen (kimse)'},],
  [{ 'word': 'ÇAMLIYAYLA', 'hint': 'Mersin iline bağlı ilçelerden biri'},],
  [{ 'word': 'KÜLHANBEYİ', 'hint': 'Kendilerine özgü giyinişi olan, argo kullanan, başıboş, haylaz delikanlı, serseri, hayta, külhani'},],
  [{ 'word': 'JAKOBENİZM', 'hint': 'Tepeden inmecilik'},],
  [{ 'word': 'ÇAKIRDİKEN', 'hint': 'Maydanozgillerden, hekimlikte kullanılan bir bitki, deveelması (Arctium tomentosum)'},],
  [{ 'word': 'ARKADAŞLIK', 'hint': 'Arkadaş olma durumu, arkadaşa yakışır davranış, omuzdaşlık, ünsiyet'},],
  [{ 'word': 'KEYFEKEDER', 'hint': 'Pek üzerinde durulmayan, önem verilmeyen'},],
  [{ 'word': 'REGÜLASYON', 'hint': 'Düzenleme, ayarlama'},],
  [{ 'word': 'AMORTİSMAN', 'hint': 'Yıpranma payı'},],
  [{ 'word': 'BİÇERDÖVER', 'hint': 'Ekin biçen, döven, taneleri ayıran, samanı deste veya balya durumuna getiren makine'},],
  [{ 'word': 'DİYETİSYEN', 'hint': 'Diyet uzmanı'},],
  [{ 'word': 'VİRANŞEHİR', 'hint': 'Şanlıurfa iline bağlı ilçelerden biri'},],
  [{ 'word': 'GELİNBOĞAN', 'hint': 'Bir tür ahlat'},],
  [{ 'word': 'GENELGEÇER', 'hint': 'Toplum tarafından kabul edilen, hemen herkesçe benimsenen'},],
  [{ 'word': 'MANİFATURA', 'hint': 'Fabrika yapımı her türlü kumaş, bez vb. dokuma'},],
  [{ 'word': 'FABRİKATÖR', 'hint': 'Fabrikacı'},],
  [{ 'word': 'VENTİLATÖR', 'hint': 'Solunum cihazı'},],
  [{ 'word': 'SARIKUYRUK', 'hint': 'Sıcak ve ılık denizlerin kıyı bölgelerinde yaşayan kemikli bir tür balık'},],
  [{ 'word': 'KLOROPLAST', 'hint': 'Yeşil bitkilerde hücrelerin içinde bulunan, klorofil moleküllerinden oluşan, karmaşık yapılı kromoplast'},],
  [{ 'word': 'LÜLEBURGAZ', 'hint': 'Kırklareli iline bağlı ilçelerden biri'},],
  [{ 'word': 'RADYOKİMYA', 'hint': 'Radyoaktif cisimleri ve onların kimyasal özelliklerini inceleyen bilim dalı'},],
  [{ 'word': 'FOTOMORFOZ', 'hint': 'Canlı varlıkların birey oluş sırasındaki gelişimi üzerinde ışığın yaptığı etki'},],
  [{ 'word': 'EBÜLYOSKOP', 'hint': 'Cisimlerin kaynama sıcaklığını tespit etmeye yarayan cihaz'},],
  [{ 'word': 'DEFTERHANE', 'hint': 'Osmanlı Devleti sınırlarındaki bütün toprak kayıtlarını içine alan ana defterlerin bulunduğu ve bunlara özgü işlerin görüldüğü daire'},],
  [{ 'word': 'MAHREMİYET', 'hint': 'Gizlilik'},],
  [{ 'word': 'MAHCUBİYET', 'hint': 'Utangaçlık'},],
  [{ 'word': 'ANESTEZİST', 'hint': 'Anestezi uzmanı'},],
  [{ 'word': 'BETELENMEK', 'hint': 'Karşı gelmek, dikleşmek, kafa tutmak'},],
  [{ 'word': 'BODOSLAMAK', 'hint': 'İleri sürmek, dayatmak'},],
  [{ 'word': 'ÇETREFİLLİ', 'hint': 'Karışık ve anlaşılması güç olan'},],
  [{ 'word': 'ALTAYİSTİK', 'hint': 'Altay grubuna giren Türk, Moğol, Mançu-Tunguz, Japon ve Korelilerin dil, edebiyat, kültür ve tarihleriyle uğraşan bilim dalı'},],
  [{ 'word': 'BAYRAMÜSTÜ', 'hint': 'Bayrama yakın zamanlarda'},],
  [{ 'word': 'AVUSTRALYA', 'hint': 'Dünya üzerinde yer alan kıtalardan biri'},],
  [{ 'word': 'AKTİNOLOJİ', 'hint': 'Güneş ışınlarının hem insan hem de bütün canlılar üzerinde etkisini inceleyen bilim dalı'},],
  [{ 'word': 'YEŞİLHİSAR', 'hint': 'Kayseri iline bağlı ilçelerden biri'},],
  [{ 'word': 'BASİRETSİZ', 'hint': 'Gerçekleri görebilmekten uzak, ileri ve uzak görüşlü olmayan, sağgörüsüz'},],
  [{ 'word': 'HARMANDALI', 'hint': 'Ege bölgesinde oynanan bir tür zeybek oyunu'},],
  [{ 'word': 'GÜZELBAHÇE', 'hint': 'İzmir iline bağlı ilçelerden biri'},],
  [{ 'word': 'PALEOGRAFİ', 'hint': 'Eski el yazılarını okuma bilgisi'},],
  [{ 'word': 'KOZMOPOLİT', 'hint': 'Çeşitli uluslardan kimseleri barındıran, içinde bulunduran'},],
  [{ 'word': 'ÇİFTLİKKÖY', 'hint': 'Yalova iline bağlı ilçelerden biri'},],
  [{ 'word': 'ÖZBESLENEN', 'hint': 'Besinini bağımsız olarak sağlayan, inorganik azot, azotlu madde ve CO2\'den protein ve karbonhidratların sentezini yapabilen (bitki), kendi beslek, ototrof'},],
  [{ 'word': 'BAYRAKALTI', 'hint': 'Askerlik'},],
  [{ 'word': 'BAĞITLAMAK', 'hint': 'Sözleşmeyle sonuçlandırmak'},],
  [{ 'word': 'PAPAZKAÇTI', 'hint': 'Bir tür iskambil oyunu'},],
  [{ 'word': 'AĞAÇKÜPESİ', 'hint': 'Hatmi'},],
  [{ 'word': 'ÇAKIRKANAT', 'hint': 'Kanatları mavi hareli bir tür ördek (Anas crecca)'},],
  [{ 'word': 'ALTINYAYLA', 'hint': 'Sivas iline bağlı ilçelerden biri'},],
  [{ 'word': 'AFRODİZYAK', 'hint': 'Cinsel duyguları veya isteği uyaran veya artıran madde'},],
  [{ 'word': 'BAŞHEMŞİRE', 'hint': 'Sağlık kuruluşlarında hemşirelik hizmetlerinin en üst düzeyde sunulması için hizmetlerin düzenlenmesinden, yürütülmesinden, denetlenmesinden sorumlu yönetici hemşire'},],
  [{ 'word': 'LAPPADANAK', 'hint': 'Sözü dolaştırmadan doğrudan söylemek'},],
  [{ 'word': 'BEYLERBEYİ', 'hint': 'Sancak beylerinin başı'},],
  [{ 'word': 'BARIŞSEVER', 'hint': 'Barışı seven, barışçı, barışçıl, sulhçu, sulhsever, sulhperver'},],
  [{ 'word': 'HACIBEKTAŞ', 'hint': 'Nevşehir iline bağlı ilçelerden biri'},],
  [{ 'word': 'GÜMÜŞSERVİ', 'hint': 'Ayın suya yansımasıyla oluşan parıltılı görünüm'},],
  [{ 'word': 'AKUPUNKTUR', 'hint': 'Vücudun belirli noktalarına genellikle altın iğne batırılarak yapılan tedavi'},],
  [{ 'word': 'ALELACAYİP', 'hint': 'Çok acayip, bambaşka'},],
  [{ 'word': 'ÜRETKENLİK', 'hint': 'Verilen emeğe ve yapılan masrafa oranla üretilen miktar, ürün verme gücü, prodüktivite'},],
  [{ 'word': 'ÇADIRUŞAĞI', 'hint': 'Maydanozgillerden, öz suyu hekimlikte kullanılan bir bitki (Dorema ammoniacum)'},],
  [{ 'word': 'BECERİKSİZ', 'hint': 'Becerisi olmayan, usta olmayan, maharetsiz'},],
  [{ 'word': 'KARABALLIK', 'hint': 'Birtakım böceklerin çıkardıkları şekerli sıvıya yapışarak yaprak, filiz ve meyvelerin kurum karası bir renkte kaplanmasına yol açan ilkel mantar'},],
  [{ 'word': 'ANTİTOKSİN', 'hint': 'İçine giren toksinleri zararsız duruma getirmek için vücudun çıkardığı madde, antitoksik'},],
  [{ 'word': 'VEZİRKÖPRÜ', 'hint': 'Samsun iline bağlı ilçelerden biri'},],
  [{ 'word': 'SALIPAZARI', 'hint': 'Samsun iline bağlı ilçelerden biri'},],
  [{ 'word': 'POTANSİYEL', 'hint': 'Gizli kalmış, henüz varlığı ortaya çıkmamış olan, gizil, Gelecekte oluşması, gelişmesi mümkün olan'},],
  [{ 'word': 'BANKAMATİK', 'hint': 'Bankaların para işlemlerini günün her saatinde otomatik olarak yapan makine'},],
  [{ 'word': 'YÜKSEKOKUL', 'hint': 'Üst düzeyde uygulayıcı meslek elemanı yetiştiren yükseköğretim kurumu, akademi'},],
  [{ 'word': 'ENSTANTANE', 'hint': 'Işıklama süresi saniyenin 1/25\'i veya daha kısa olan hızlı bir hareketi çekme yöntemi'},],
  [{ 'word': 'DEKORASYON', 'hint': 'Dekor yapma işi, Bir yeri süsleme'},],
  [{ 'word': 'DELİMSİREK', 'hint': 'Delice'},],
  [{ 'word': 'SULTANGAZİ', 'hint': 'İstanbul iline bağlı ilçelerden biri'},],
  [{ 'word': 'KÖPEKAYASI', 'hint': 'Ballıbabagillerden, çiçekleri sap çevresinde demet durumunda toplanmış, güzel kokulu birçok türü olan bir bitki (Marrubium vulgare)'},],
  [{ 'word': 'ARNAVUTKÖY', 'hint': 'İstanbul iline bağlı ilçelerden biri'},],
  [{ 'word': 'REFERANDUM', 'hint': 'Halk oylaması'},],
  [{ 'word': 'DEMİRHİNDİ', 'hint': 'Baklagillerden, odunu oldukça sert olan, sıcak iklimlerde yetişen bir ağaç (Tamarindus indica)'},],
  [{ 'word': 'CEPHANELİK', 'hint': 'Cephanenin saklanmasına yarar kapalı ve korunmuş yer'},],
  [{ 'word': 'HAYIRSEVER', 'hint': 'Yoksullara, düşkünlere, yardıma muhtaç olanlara iyilik ve yardım etmesini seven, iyiliksever, yardımsever, hayırperver'},],
  [{ 'word': 'BAŞREJİSÖR', 'hint': 'Başyönetmen'},],
  [{ 'word': 'SANCAKTEPE', 'hint': 'İstanbul iline bağlı ilçelerden biri'},],
  [{ 'word': 'AGRANDİSÖR', 'hint': 'Büyülteç'},],
  [{ 'word': 'ARJANTİNLİ', 'hint': 'Arjantin’de yaşayan halktan veya bu halkın soyundan olan kimse'},],
  [{ 'word': 'DENİZAYISI', 'hint': 'Boyu 1,5-2 metre olan, uzun ve yumuşak tüylü postu beğenilen, bitkiyle beslenen bir deniz memelisi (Arctocephalus ursinus)'},],
  [{ 'word': 'NEMALANMAK', 'hint': 'Beslenmek'},],
  [{ 'word': 'DELİBOYNUZ', 'hint': 'Erguvan'},],
  [{ 'word': 'DEPREMZEDE', 'hint': 'Depremde zarar görmüş kimse'},],
  [{ 'word': 'SİVRİHİSAR', 'hint': 'Eskişehir iline bağlı ilçelerden biri'},],
  [{ 'word': 'ÜNİVERSİTE', 'hint': 'Bilimsel özerkliğe ve kamu tüzel kişiliğine sahip, yüksek düzeyde eğitim, öğretim, bilimsel araştırma ve yayın yapan fakülte, enstitü, yüksekokul vb. kuruluş ve birimlerden oluşan öğretim kurumu, darülfünun'},],
  [{ 'word': 'KONKORDATO', 'hint': 'Anlaşmalı iflas'},],
  [{ 'word': 'ÇARKÇIBAŞI', 'hint': 'Vapurlarda birinci çarkçı'},],
  [{ 'word': 'MECBURİYET', 'hint': 'Zorunluluk'},],
  [{ 'word': 'GAYRİMEŞRU', 'hint': 'Yolsuz, yasaya veya töreye aykırı, Evlilik dışı'},],
  [{ 'word': 'HACIYATMAZ', 'hint': 'Yere nasıl bırakılırsa bırakılsın, dibinde bulunan ağırlık sebebiyle dik bir durum alan oyuncak'},],
  [{ 'word': 'PERSPEKTİF', 'hint': 'Bakış açısı'},],
  [{ 'word': 'ENGİZİSYON', 'hint': 'Orta Çağda, Katoliklerde katı din inançlarına karşı gelenleri cezalandırmak için kurulan kilise mahkemelerinin adı'},],
  [{ 'word': 'JEOPOLİTİK', 'hint': 'Coğrafya, ekonomi, nüfus vb.nin bir devletin politikası üzerindeki etkisi'},],
  [{ 'word': 'BİLİMSEVER', 'hint': 'Bilimi seven, bilimle uğraşan (kimse)'},],
  [{ 'word': 'İNTERFERON', 'hint': 'Hücrelerin virüslere karşı oluşturdukları özel savunma maddesi'},],
  [{ 'word': 'ÇİĞİNDİRİK', 'hint': 'İki ucuna su kabı, yoğurt tablası vb. taşınacak şeyler asılarak omza alınan ağaç, omuzluk'},],
  [{ 'word': 'HARİCİYECİ', 'hint': 'Dış siyaset ile uğraşan meslek adamı'},],
  [{ 'word': 'OKSİDASYON', 'hint': 'Paslanma'},],
  [{ 'word': 'BOĞAZKESEN', 'hint': 'Bir boğazı savunmak için deniz kıyısında yapılan hisar'},],
  [{ 'word': 'İĞDEGİLLER', 'hint': 'İki çeneklilerden, örneği iğde olan bitki familyası'},],
  [{ 'word': 'EKZOTERMİK', 'hint': 'Isıveren'},],
  [{ 'word': 'CUKKALAMAK', 'hint': 'Hakkı olmayan bir şeyi alıp sahiplenmek'},],
  [{ 'word': 'BASBARİTON', 'hint': 'Basın çıkamadığı ince tonlara çıkabilen, buna rağmen basın indiği kalın ve tok tonlara inemeyen sesi olan sanatçı'},],
  [{ 'word': 'DARMADUMAN', 'hint': 'Karmakarışık'},],
  [{ 'word': 'BEYZADELİK', 'hint': 'Soyluluk'},],
  [{ 'word': 'FİBRİNOJEN', 'hint': 'Pıhtılaşma sırasında fibrine dönüşen bir kan proteini'},],
  [{ 'word': 'KARBÜRATÖR', 'hint': 'Patlamalı motorlarda akaryakıtı buharlaştırıp hava ile karışmasını sağlayan cihaz'},],
  [{ 'word': 'PROFİTEROL', 'hint': 'Arasında krema bulunan özel yuvarlak toplar üzerine sıcak çikolata dökülerek yapılan bir tatlı türü'},],
  [{ 'word': 'PROLETARYA', 'hint': 'Emekçi sınıfı'},],
  [{ 'word': 'UYKUCUBAŞI', 'hint': 'Uykuyu çok sevenler için şakayla söylenen söz'},],
  [{ 'word': 'ELEŞTİRMEN', 'hint': 'Eleştiri yapan kimse, eleştirmeci, eleştirimci, tenkitçi, münekkit'},],
  [{ 'word': 'İSKENDERUN', 'hint': 'Hatay iline bağlı ilçelerden biri'},],
  [{ 'word': 'TAVUKGÖĞSÜ', 'hint': 'Lifleri yumuşayıncaya kadar haşlanmış, didiklenmiş tavuk göğüs etinin pirinç ve süt ile koyulaşıncaya kadar pişirilmesiyle yapılan muhallebiye şeker ve tavuk suyu katılarak hazırlanan bir tatlı türü'},],
  [{ 'word': 'PUANTİYELİ', 'hint': 'Noktalı, benekli (kumaş)'},],
  [{ 'word': 'KIZILÖTESİ', 'hint': 'Işık tayfında kırmızı alanın ötesindeki alanda yayılmış ısı ışınlarından oluşan, gözle görülmeyen ışınım, enfraruj'},],
  [{ 'word': 'HİPERAKTİF', 'hint': 'Aşırı etkin'},],
  [{ 'word': 'ALACAKARGA', 'hint': 'Saksağan'},],
  [{ 'word': 'CIRDAVALLI', 'hint': 'Cırdaval ile savaşan atlı, mızraklı asker'},],
  [{ 'word': 'ASTROFİZİK', 'hint': 'Yıldız fiziği'},],
  [{ 'word': 'KARGABURNU', 'hint': 'Sanayide küçük ve yuva içine yerleştirilmiş vidaları sökmeye yarayan ince, uzun ağızlı alet'},],
  [{ 'word': 'BİREYCİLİK', 'hint': 'Bütüne, genele değil de bireye, tek olana üstünlük tanıyan görüş, ferdiyetçilik, individüalizm'},],
  [{ 'word': 'ORTOPEDİST', 'hint': 'Ortopedi uzmanı'},],
  [{ 'word': 'BALIKSIRTI', 'hint': 'Balık iskeleti biçiminde birbirine paralel ve çapraz çizgili kumaş deseni'},],
  [{ 'word': 'BERİBENZER', 'hint': 'Sıradan, bayağı, alelade'},],
  [{ 'word': 'ANTAGONİST', 'hint': 'Düşman'},],
  [{ 'word': 'İSPANYOLCA', 'hint': 'İspanya\'da, Brezilya dışındaki Latin Amerika\'da ve İspanyolların hâkim olduğu bölgelerde yaşayanların kullandığı dil'},],
  [{ 'word': 'DEVEELMASI', 'hint': 'Çakırdiken'},],
  [{ 'word': 'ANTİSİKLON', 'hint': 'Yüksek basınçlı atmosfer kütlesi'},],
  [{ 'word': 'ATEŞPEREST', 'hint': 'Ateşe tapan'},],
  [{ 'word': 'BENİMSEMEK', 'hint': 'Bir şeyi kendine mal etmek, sahip çıkmak, kabullenmek, tesahup etmek'},],
  [{ 'word': 'ENJEKSİYON', 'hint': 'Vücutta damar, doku, kanal veya boşluk içine enjektör aracılığıyla sıvı veya ilaç verme, zerk etme'},],
  [{ 'word': 'UYUŞTURUCU', 'hint': 'Uyuşturma özelliği olan, uyuşturan (madde), narkotik'},],
  [{ 'word': 'HIDIRELLEZ', 'hint': 'Hızır ve İlyas peygamberlerin her yıl buluştuklarına inanılan 6 Mayıs günü'},],
  [{ 'word': 'BAŞDENETÇİ', 'hint': 'En üst düzeydeki denetçi, başmurakıp'},],
  [{ 'word': 'NURUÇEŞMİM', 'hint': 'Gözümün nuru'},],
  [{ 'word': 'ENFEKSİYON', 'hint': 'Organizmada hastalığa yol açan mikrop, virüs, parazit vb. etkenlerin genel veya yerel gelişmesi, yayılması'},],
  [{ 'word': 'GREKOROMEN', 'hint': 'Yüze, boğaza dokunmama, belden aşağısını tutmama, ayaklarla oyun yapmama vb. kuralları olan güreş türü'},],
  [{ 'word': 'ALTIPARMAK', 'hint': 'Bir tür iri palamut balığı'},],
  [{ 'word': 'FİLİZKIRAN', 'hint': 'Mayıs ayında ağaçların filizlendiği mevsimde esen bir fırtına'},],
  [{ 'word': 'BAĞIŞIKLIK', 'hint': 'Bazı mikroplara karşı aşı veya doğal yolla kazanılmış direnç durumu'},],
  [{ 'word': 'YAKINSAMAK', 'hint': 'Bir şeyin yakın zamanda olacağını düşünmek, olmasını yakın görmek'},],
  [{ 'word': 'NAMÜTENAHİ', 'hint': 'Sonsuz, ucu bucağı olmayan'},],
  [{ 'word': 'BARPARALEL', 'hint': 'Düşey direkler üzerine paralel olarak tutturulmuş iki tahta çubuktan oluşmuş jimnastik aracı'},],
  [{ 'word': 'FEDERASYON', 'hint': 'Savunma ve dış politika alanında dayanışma amacıyla birden fazla devletin bir birlik devleti içinde birleşmesi'},],
  [{ 'word': 'KRONOMETRE', 'hint': 'Süreölçer'},],
  [{ 'word': 'HELİKOPTER', 'hint': 'Dik iniş ve çıkış yapabildiği için dar yerlerde de kullanılabilen, tepeden pervaneli, uçan taşıt'},],
  [{ 'word': 'NORMALALTI', 'hint': 'Bir eğriye ilişkin normalin, bir doğruyu kestiği nokta ile normalin ayağı arasındaki parçanın o doğru üzerindeki iz düşümü'},],
  [{ 'word': 'ELEKTROFİL', 'hint': 'Bir atom veya iyondan elektron alabilen, onunla elektron paylaşabilen madde'},],
  [{ 'word': 'KRİPTOLOJİ', 'hint': 'Gizli yazılar, şifreli belgeler bilimi veya incelemesi'},],
  [{ 'word': 'BASKLARNET', 'hint': 'Kalın sesli klarnet'},],
  [{ 'word': 'CİNSİLATİF', 'hint': 'Güzel, alımlı, hoşa giden kadın'},],
  [{ 'word': 'BARDAKALTI', 'hint': 'Bardağın konulduğu yeri kirletmemesi için kullanılan, genellikle örgü, kâğıt veya plastik örtü'},],
  [{ 'word': 'ELEKTROSAZ', 'hint': 'Elektrikten yararlanılarak sesi yükseltilen saz'},],
  [{ 'word': 'ÇEKİMÖLÇER', 'hint': 'Çekim kuvvetlerini ölçmeye yarayan araç'},],
  [{ 'word': 'BELGEGEÇER', 'hint': 'Yazılı, bilgi ve belgelerin telefon sistemi vasıtasıyla bir yerden bir yere iletilmesini anında sağlayan araç, belgeç, faks'},],
  [{ 'word': 'BAŞKALAŞIM', 'hint': 'Bir kütlenin fiziki ve kimyasal özelliklerinin değişmesi, istihale, metamorfizm'},],
  [{ 'word': 'ELEKTROFON', 'hint': 'Fonograf kayıtlarını okumak ve elektrik akımının aracılığıyla yükselterek sese çevirmek için gerekli araçları içinde toplayan cihaz'},],
  [{ 'word': 'MAHPUSHANE', 'hint': 'Cezaevi'},],
  [{ 'word': 'JEODİNAMİK', 'hint': 'Volkan, deprem, aşınma vb. etkenlerle yer kabuğunda oluşan değişikliklerin incelenmesi'},],
  [{ 'word': 'KOYULHİSAR', 'hint': 'Sivas iline bağlı ilçelerden biri'},],
  [{ 'word': 'DRAMATURJİ', 'hint': 'Oyun yazma ve yönetme bilgisi'},],
  [{ 'word': 'ETNOGRAFYA', 'hint': 'Kavimleri karşılaştırarak inceleyen, kültür oluşumlarını araştıran bilim, budun betimi, kavmiyat'},],
  [{ 'word': 'PATAVATSIZ', 'hint': 'Sözlerinin nereye varacağını düşünmeden saygısızca konuşan, davranışlarına dikkat etmeyen (kimse)'},],
  [{ 'word': 'ÇAKIRKEYİF', 'hint': 'Yarı sarhoş'},],
  [{ 'word': 'SEKRETARYA', 'hint': 'Bir kurum veya partide programlanmış ve rutin işlere ait süreçlerin yönlendirilmesinin, sevk ve idaresinin yapıldığı bölüm'},],
  [{ 'word': 'YUMURTALIK', 'hint': 'Canlılarda dişi üreme hücrelerini veren organ, mebiz'},],
  [{ 'word': 'HIYARŞEMBE', 'hint': 'Baklagillerden, siyah renkte olan meyvelerinin içinde çekirdeklerden başka hekimlikte kullanılan bir öz bulunan bitki, Hint hıyarı (Cassia fistula)'},],
  [{ 'word': 'İNTERAKTİF', 'hint': 'Etkileşimli'},],
  [{ 'word': 'RADYOFİZİK', 'hint': 'Radyoelektriğe ilişkin olayları inceleyen bilim dalı'},],
  [{ 'word': 'VANTİLATÖR', 'hint': 'Sıcak ve durgun havayı dalgalandırarak esinti sağlayan veya böyle bir ortama temiz hava üfleyen alet'},],
  [{ 'word': 'DENİZİNEĞİ', 'hint': 'Amerika ve Afrika\'nın tropikal kıyı sularında yaşayan, 2-3 metre boyunda deniz memelisi (Hydrodamalis gigas)'},],
  [{ 'word': 'AZOTOMETRE', 'hint': 'Azotölçer'},],
  [{ 'word': 'PINARHİSAR', 'hint': 'Kırklareli iline bağlı ilçelerden biri'},],
  [{ 'word': 'HAKKANİYET', 'hint': 'Hak ve adalete uygunluk, doğruluk, nasfet'},],
  [{ 'word': 'FARMAKOLOG', 'hint': 'İlaç bilimi ile uğraşan, ilaç bilimi uzmanı'},],
  [{ 'word': 'FOTOTERAPİ', 'hint': 'Işık kullanılarak yapılan tedavi'},],
  [{ 'word': 'BAŞKOMUTAN', 'hint': 'Savaşta bir devletin bütün kara, deniz ve hava kuvvetlerini yöneten büyük komutan, başkumandan, serdar'},],
  [{ 'word': 'FAHRENHAYT', 'hint': 'Erimekte olan buzun sıcaklığını 32 °C, kaynar suyun buhar sıcaklığını 212 °C\'de gösterebilecek biçimde derecelenmiş bulunan bir termometre türü'},],
  [{ 'word': 'TOPRAKLAMA', 'hint': 'Elektrik devresinde veya elektrikle çalışan bir araçta bir ucu toprakla birleştirme işi'},],
  [{ 'word': 'ANTİSEPTİK', 'hint': 'Antisepsi yapmak için kullanılan (madde)'},],
  [{ 'word': 'İMARETHANE', 'hint': 'Yoksullara ve öğrencilere yiyecek dağıtmak için kurulmuş hayır kurumu, imaret'},],
  [{ 'word': 'DALKURUTAN', 'hint': 'Kabuk altındaki odun katında oyuklar açarak dişbudak sürgünlerini ve zeytin dallarını kurutan kın kanatlı böcek (Hylesinus oleiperda)'},],
  [{ 'word': 'SOĞUKKANLI', 'hint': 'Olaylara ve gelişmelere sakin, ılımlı ve temkinli yaklaşan (kimse), serinkanlı, itidal sahibi'},],
  [{ 'word': 'AKÜMÜLATOR', 'hint': 'Elektrik enerjisini kimyasal enerji olarak depolayan, istenildiğinde bunu elektrik enerjisi olarak veren cihaz, akımtoplar, akü'},],
  [{ 'word': 'LİTOGRAFYA', 'hint': 'Taş basması'},],
  [{ 'word': 'KOREOGRAFİ', 'hint': 'Bir baleyi oluşturan adım, figür ve anlatımların bütünü'},],
  [{ 'word': 'BACAKKIRAN', 'hint': 'Nemli bölgelerde yetişen yeşilimsi sarı çiçekli bir bitki (Narthecium)'},],
  [{ 'word': 'ELEKTROLİT', 'hint': 'Elektroliz işlemiyle çözülen madde'},],
  [{ 'word': 'ALIKONULMA', 'hint': 'Alıkonulmak işi, mevkufiyet'},],
  [{ 'word': 'REPERTUVAR', 'hint': 'Bir tiyatro kurulunun oynamak için seçip hazırlamış olduğu oyunların listesi'},],
  [{ 'word': 'DEVRİHİNDİ', 'hint': 'Türk müziğinde bir küçük usul'},],
  [{ 'word': 'FOTOMONTAJ', 'hint': 'Bir konu üzerindeki eksik bölümleri tamamlamak veya daha çok konuyu bir araya toplamak için birkaç fotoğrafın birleştirilmesi'},],
  [{ 'word': 'ASİDİMETRE', 'hint': 'Asitölçer'},],
  [{ 'word': 'DARMADAĞIN', 'hint': 'Çok dağınık ve karışık, darmadağınık, tarumar'},],
  [{ 'word': 'HASANBEYLİ', 'hint': 'Osmaniye iline bağlı ilçelerden biri'},],
  [{ 'word': 'ANJİYOLOJİ', 'hint': 'Kan ve ak kan damarlarını inceleyen bilim dalı'},],
  [{ 'word': 'LALETTAYİN', 'hint': 'Sıradan, Herhangi bir'},],
  [{ 'word': 'DENDROLOJİ', 'hint': 'Ağaç bilimi'},],
  [{ 'word': 'ALTUNHİSAR', 'hint': 'Niğde iline bağlı ilçelerden biri'},],
  [{ 'word': 'JENERASYON', 'hint': 'Kuşak'},],
  [{ 'word': 'HIYARAĞASI', 'hint': 'Görgüsüz, kaba saba, yontulmamış (kimse)'},],
  [{ 'word': 'AKŞAMÜZERİ', 'hint': 'Akşamüstü'},],
  [{ 'word': 'DEDÜKSİYON', 'hint': 'Tümdengelim'},],
  [{ 'word': 'BETİMLEMEK', 'hint': 'Bir nesnenin, kendine özgü niteliklerini tam ve açık bir biçimde söz veya yazı ile anlatmak, tasvir etmek'},],
  [{ 'word': 'DEFİBRATÖR', 'hint': 'Yongaları liflerine ayrıştıran özel alet'},],
  [{ 'word': 'GÖLMARMARA', 'hint': 'Manisa iline bağlı ilçelerden biri'},],
  [{ 'word': 'BURUNDURUK', 'hint': 'Hayvanları nallarken ısırmaması için dudaklarını kıstırmaya yarayan kıskaç, yavaşa'},],
  [{ 'word': 'ANAKRONİZM', 'hint': 'Tarih yanılgısı'},],
  [{ 'word': 'UTANGAÇLIK', 'hint': 'Sıkılganlık, mahcubiyet'},],
  [{ 'word': 'VAKFIKEBİR', 'hint': 'Trabzon iline bağlı ilçelerden biri'},],
  [{ 'word': 'HOROZAYAĞI', 'hint': 'Tüfekten boş kovanı çıkarmaya yarayan alet'},],
  [{ 'word': 'ACEMBORUSU', 'hint': 'Canlı kırmızı renkli çiçek açan, uzun boylu bir tür süs bitkisi (Bignonia radicams)'},],
  [{ 'word': 'DALGAKIRAN', 'hint': 'Kıyıdaki yapıları, tekneleri, dalgaların yıpratıcı etkisinden korumak veya gemilerin yük alıp boşaltmasını sağlamak amacıyla liman ve iskele önlerine yapılan uzun set'},],
  [{ 'word': 'KOOPERATİF', 'hint': 'Üreticilerin, aracıyı ortadan çıkararak ürünlerini daha iyi şartlarda pazarlamak için kurdukları ortaklık'},],
  [{ 'word': 'KAYIŞKIRAN', 'hint': 'Baklagillerden, kökleri toprağa derince girdiği için tarlalar sürülürken sabanı tutan, çiçekleri kırmızı bir bitki, sabankıran (Onosis spinosa)'},],
  [{ 'word': 'ANDROSEFAL', 'hint': 'Sadece başı insan başına benzeyen (hayvan)'},],
  [{ 'word': 'MİKRODALGA', 'hint': 'Boyları 1 milimetre ile 1 metre arasında değişen elektromanyetik dalga'},],
  [{ 'word': 'ÇATALPINAR', 'hint': 'Ordu iline bağlı ilçelerden biri'},],
  [{ 'word': 'ÇAKIRDOĞAN', 'hint': 'Yırtıcı kuşlardan bir tür doğan, tuğrul (Accipiter gentilis)'},],
  [{ 'word': 'BEŞİBİRLİK', 'hint': 'Kadınların süs için takındıkları, beş tam altının bir arada bulunduğu süs eşyası, beşibiryerde, beşibirarada'},],
  [{ 'word': 'CİHANBEYLİ', 'hint': 'Konya iline bağlı ilçelerden biri'},],
  [{ 'word': 'KOLESTEROL', 'hint': 'Kanda ve büyük ölçüde ödde bulunan, besinlerle alınan sterol, kolesterin'},],
  [{ 'word': 'BAŞKALDIRI', 'hint': 'Herhangi bir amaçla kurulu düzene veya devlet güçlerine karşı gelme, başkaldırma, ayaklanma, isyan'},],
  [{ 'word': 'VAFTİZHANE', 'hint': 'Vaftiz yapılan yer'},],
  [{ 'word': 'NEOLİBERAL', 'hint': 'Bir yandan devletin piyasaya olan müdahalesini en az düzeye indirirken diğer yandan kuralsızlık teorisi ile özel sermayeye her türlü imkânın sağlanmasını hedefleyen (sistem)'},],
  [{ 'word': 'KARİZMATİK', 'hint': 'Etkileyici'},],
  [{ 'word': 'GÜLBEŞEKER', 'hint': 'Gül çiçeği ve şeker ile yapılan macun kıvamında bir reçel türü'},],
  [{ 'word': 'KUZUKULAĞI', 'hint': 'Karabuğdaygillerden, nemli yerlerde yetişen, yaprakları salata olarak kullanılan, çiçekleri iki evcikli ve kırmızımtırak bir bitki, ekşikulak (Rumex acetosa)'},],
  [{ 'word': 'EDİRNEKARİ', 'hint': 'Tahta üzerine boya ve altın yaldız ile yapılan nakış'},],
  [{ 'word': 'DİREKSİYON', 'hint': 'Taşıta istenilen yönü vermeye ve taşıtı belirli bir doğrultuda götürmeye yarayan düzenek, yönelteç'},],
];